---
- name: Setting host facts using complex arguments
  set_fact:
    gitlab_baseurl_api: "{{ gitlab_url }}{{ gitlab_api_context_path }}"
- name: Setting host facts to use gitlab api v4 variables
  set_fact:
    gitlab_runner_api: "{{ gitlab_baseurl_api }}/user/runners"

- name: Create runner instance on gitlab
  uri:
    url: "{{ gitlab_runner_api }}"
    headers:
      PRIVATE-TOKEN: "{{ gitlab_private_access_token }}"
    method: POST
    return_content: yes
    status_code: 201
    body:
      runner_type: "instance_type"
      run_untagged: true
      description: "runner-{{ inventory_hostname }}-docker"
      tag_list: ["docker"]
      access_level: "not_protected"
    body_format: form-urlencoded
  register: gitlab_runner_token

- debug:
    msg: "{{ gitlab_runner_token.json['token'] }}"

- name: "Gitlab verify"
  shell: 
    cmd: gitlab-runner verify --name {{ inventory_hostname }}-docker
  register: gitlab_runner_exist
  failed_when: false

- name: "Gitlab register docker executor"
  shell: 
    cmd: |
      gitlab-runner register \
      -r={{ gitlab_runner_token.json['token'] }} \
      --name={{ inventory_hostname }}-docker  \
      --non-interactive \
      --request-concurrency={{ runner_concurrent_jobs_num | default('5') }} \
      --url={{ gitlab_url }} \
      --clone-url={{ gitlab_clone_url }} \
      --executor=docker \
      --docker-image="alpine:latest" \
      --docker-tlsverify=false \
      --docker-disable-entrypoint-overwrite=false \
      --docker-oom-kill-disable=false \
      --env="DOCKER_TLS_CERTDIR=" \
      --docker-privileged=true \
      --tag-list="docker" \
      --docker-extra-hosts={{ gitlab_runner_extra_host | join(' ') }} \
      --docker-volumes={{ gitlab_runner_docker_volumes | join(' ') }}
  when: gitlab_runner_exist.rc == 1